### PR TITLE
Added support for /etc/dnsmasq.d/, Added a HealthCheck, Added a KeyCheck

### PR DESCRIPTION
**Pull request by goose-ws**
Because local `CNAME` records are stored in `/etc/dnsmasq.d/` it's necessary to also be able to sync that folder.

Because the `/etc/dnsmasq.d/01-pihole.conf` and `/etc/pihole/piholt-FTL.db` files are client-dependent, they should not be synced.

Added a health check for if `rsync` fails.

Added a way to prevent the question of accepting a key on first ssh, if it's not already in `~/.ssh/known_hosts`.

Pointed to the `~/.ssh/id_ed25519` specifically, as pointing to the `~/.ssh/` directory in general will not work if there is an `~/.ssh/config` file not owned by `root`.

### CODE REVIEW

**Comment by ShiromMakkad** [comment]
It's been a while since I've used this container, so I'll trust everything works. These are all great additions, and splitting the client-dependent files should clean up the massive error log this container causes. 

Couple of notes:
- I don't like the idea of having a separate `DNSMASQCLIENTDIR` because it's just another thing for the end user to worry about. If we know that the target directory is `/etc/dnsmask.d/`, can't we just get the client ip from the `CLIENTDIR` variable? I don't see why you'd need to specify a directory that's not `/etc/dnsmask.d/`. 
- The docker compose example needs to have the new environment variables in it if we're going that route
- I'd rather use `id_rsa` as the example since it's more ubiquitous and is better supported. 

I can update the examples/docs, but I'd like to hear your thoughts on the `DNSMASQCLIENTDIR` variable.

**Comment by goose-ws** [comment]
Unfortunately, my pull request only partly solves some of the problems. I'm using the official `pihole:pihole` repository, which is presents a few issues:

They recommend running a volume setup that's essentially:

```
 -v ${HOME}/etc-pihole/:/etc/pihole/
 -v ${HOME}/etc-dnsmasq/:/etc/dnsmasq.d/
```

The split directories prevent one from just mount something like `-v ${HOME}/etc:/etc`, as there's a lot of other stuff in `/etc` that the container needs, that wouldn't be present on the host filesystem.

The thing is, their repo is based on s6, which does not let one modify the UID/GID running the container. So on the host, the `${HOME}/etc-pihole/` and `${HOME}/etc-dnsmasq/` are owned by UID/GID 999:999 and 0:0 respectively. Beyond that, most of the files in those directories are also owned by root (0:0), with the exception of a few that are also 999:999.

Because this container runs as root, it's not an issue. But the issue is that unless the receiving ssh user on the remote file system is root, it won't be able to write to the respective directories on the remote file system. In short:

` [Pi-Hole Master FS 0:0] ==> [Pi-Hole Sync 0:0] ==SSH==> [Remote FS [goose 1001:1001]] ==>X [Pi-Hole Slave FS 0:0]`

I've been debating how to solve this. It could be possible to chmod 666/777 on all the files/directories respectively. While an elegant one-step fix, terrible security-wise. The best solution I have so far is implementing an additional container running at UID/GID `0:0` on the `Pi-Hole Slave` device, so that the changes go from:

` [Pi-Hole Master FS 0:0] ==> [Pi-Hole Sync Sender 0:0] ==SSH==> [Remote FS [goose 1001:1001]] ==> [Pi-Hole Sync Receiver 0:0]==> [Pi-Hole Slave FS 0:0]`

Essentially, instead of `rsync`ing the file directly to the `${HOME}/etc-pihole/` of the slave device where they cannot be written by my UID/GID of 1000:1000 and would therefore fail to transfer, instead put them in something like `${HOME}/tmp/etc-pihole/`. The `Pi-Hole Sync Receiver` container would have both `${HOME}/etc-pihole/` and `${HOME}/tmp/etc-pihole/` volumes mounted, and would be running as UID/GID 0:0. By running as root, it could watch for `write_close` events to the `${HOME}/tmp/etc-pihole/` directory and then `chown 0:0` (Or `chown 999:999`, it would be good to first check permissions on the existing file before replacing it), and then move it from the `${HOME}/tmp/etc-pihole` to the real `${HOME}/etc-pihole`.

Overengineered? Perhaps. But best solution I've been able to think up so far. I haven't tried to implement this yet, I'm waiting on my second RPi to be delivered.

Regarding the keys, I suggested `ed25519`, as I recently found out my 11 year old `rsa` key appears to be [depreciated](https://security.stackexchange.com/questions/226131/openssh-declares-ssh-rsa-deprecated-what-do-i-do-next), so I've switched to `ed25519`

**Comment by ShiromMakkad** [comment]
That's a pretty good reason to keep the split directories.

Regarding the `ed25519` issue, `ed25519` is the better algorithm, but it's not like `rsa` is outdated. The link you sent was for `rsa` keys based on `SHA1`, which, if you generate a key today, `rsa` will not use. Modern `rsa` is pretty secure, and I've had compatibility issues with `ed25519`. 

Can you add the examples in for the `DNSMASQCLIENTDIR` since I've not used it before? I'll merge afterwards.

**Review by goose-ws — COMMENTED** [review]
I've updated the README as appropriate; however, until a solution is implemented to fix the issues with trying to write to a `root` owned directory with a non-root account, it won't do much good.

**Comment by ShiromMakkad** [comment]
Couldn't you create a root user on the client pihole and ssh into that user? Then it would be able to write to any root folders. I'm no Linux permissions expert, but I'd assume there's a way to give a user root privileges over only some directories.

**Comment by goose-ws** [comment]
Giving direct ssh access to the root user is generally a terrible idea, security-wise.

I have an idea that doesn't involve creating a whole new purposed container, expect another merge request in a week or so while I bang out some tests and trial-and-error my idea into submission.

**Pull request merged**
