### PR TITLE
Sync while maintaining UID/GID for files

### PR DESCRIPTION
**Pull request by goose-ws**
I slimmed the image down by switching it from Debian to Alpine

I re-configured it so that you now much run a container on both the sender, and the receiver, but the trade off is that there is now a containerized root user which you can send to, which allows for preservation of the UID/GID of files, until Pi-Hole modifies their docker containers to allow running as non-root.

### CODE REVIEW

**Review by goose-ws — COMMENTED** [review]
Me and my stupid fat copy/pasting fingers

**Review by goose-ws — COMMENTED** [review]
Okay it's right this time I promise

**Review by goose-ws — COMMENTED** [review]
I swear this is the last one

**Comment by ShiromMakkad** [comment]
Everything looks good, great docs too. These changes won't break compatibility for a Pihole running outside of Docker, right? I don't want to require users who are not running Docker on the secondary Pihole to use the receiver container.

**Comment by goose-ws** [comment]
> These changes won't break compatibility for a Pihole running outside of Docker, right?

They will not; however, my changes could be considered "overkill" for a user running Pi-Hole outside of Docker, as those users have the inherent ability to run Pi-Hole as whatever UID/GID they choose, instead of being forced to use 0:0 and 999:999. Assuming the UID/GID is the same on the bare-metal of both the sender and receiver, this will still function just fine. If the UID/GID were different, then it could break things, but that would have been just as likely with the original implantation. If anyone files a bug report for that, let me know, I'll patch in a UID/GID modifier.

**Comment by ShiromMakkad** [comment]
Sounds good, I just wanted to make sure my current setup, where I have a server running Docker sending my config to a Raspberry Pi without Docker, will still work without much additional configuration. 

Also, I **really** like how the sending an receiving container are the same image, so it's easier to maintain. Also, I just generally like what you've done with the container. 

I'll merge this and get it pushed to DockerHub

**Pull request merged**
